apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    name: hello
  # annotations:
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
        resources:
          requests:
            ephemeral-storage: "2Gi"
          limits:
            ephemeral-storage: "4Gi"
