apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: test
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "name": "hello-test"
  delay:
    latency: "90ms"
    correlation: "25"
    jitter: "90ms"
  duration: "10s"
  scheduler:
    cron: "@every 15s"

