apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-example
  namespace: test
spec:
  action: corrupt
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "name": "hello-test"
  corrupt:
    corrupt: "40"
    correlation: "25"
  duration: "10s"
  scheduler:
    cron: "@every 15s"

