apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test-deploy
  labels:
    name: hello-test
  annotations:
    litmuschaos.io/chaos: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-test
  template:
    metadata:
      labels:
        name: hello-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
