apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-disk-fill
  namespace: default
spec:
  jobCleanUpPolicy: delete
  monitoring: false
  appinfo: 
    appns: default 
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: "name=hello" 
    appkind: deployment
  chaosServiceAccount: nginx 
  experiments:
    - name: disk-fill
      spec:
        components:
        # specify the fill percentage according to the disk pressure required
        - name: FILL_PERCENTAGE
          value: "80"
        - name: TARGET_CONTAINER
          value: nginx
        - name: TOTAL_CHAOS_DURATION
          value: "60"
